export { default as Navigation } from "./Navigation";
export { default as Main } from "./Main";
export { default as About } from "./About";
export { default as Education } from "./Education";
export { default as Skill } from "./Skill";
export { default as Project } from "./Project";
export { default as Resume } from "./Resume";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
